#!/bin/sh

echo "This script installs and configures datastore-server in three steps:"
echo "   1. datastore-server configuration file"
echo "   2. stunnel4 configuration for datstore-server"
echo "   3. MySQL database for datastore-server"
echo "\npress [ENTER] to continue"
read a

